spring.application.name=api


# Configura a porta da aplicação
server.port=8888


# Desabilita (por enquanto) o acesso a banco de dados
#spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
spring.jpa.hibernate.ddl-auto=validate

spring.datasource.url=jdbc:postgresql://pooled.db.prisma.io:5432/postgres?sslmode=require
spring.datasource.username=fb70a9493ffdeedb222360e1ef35e1d5a7f4908e6a0d6f8d69f131dec9c6417c
spring.datasource.password=sk_-bPF0pVXjLuyaUjz8Dy9U